### ISSUE TITLE
refactor sign up form styles to use Tailwind

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.blissri.com#14]
## Summary
Coming out of AnalogStudiosRI/www.blissfestri.com#19 , some of the [styles for the Signup Form](https://github.com/AnalogStudiosRI/www.blissfestri.com/blob/main/src/styles/main.css#L8) were captured as vanilla CSS and not Tailwind styles.  It would be good if these styles could be adapted to Tailwind classes just to help keep all the relevant code in one place and stay "idiomatic" to Tailwind.
```css
#signup-form {
  border: 15px solid transparent;
  border-image-source: url('/assets/images/screen-form-edge.png');
  border-image-repeat: stretch;
  border-image-slice: 30;
  border-image-width: 20px;
  border-image-outset: 9px;
}
```

## Details
I think this may require upgrading to Tailwind v3, as I think I only see support for this CSS in the v3 docs?  I guess the main thing is to figure out if Tailwind can even accomplish this, in particular I think the tricky part would be the background image, but I think those can be customized too through _tailwind.config.js_?

(If someone wants to try this out, I can help getting a PR setup up with Tailwind 3 added to the project)
